# Generated by Django 5.2.8 on 2025-12-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_email_student_enrollment_dare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enrollment_dare',
            new_name='enrollment_date',
        ),
    ]
